### ISSUE TITLE
After update tshield from 0.10 to 0.11 on startup it terminate with exception

### ISSUE THREAD

**Issue by eduardongarcia** [diegorubin/tshield#30]
**Describe the bug**
After update tshield from 0.10 to 0.11 on startup it terminate with exception in sessions.rb
`registered': undefined local variable or method 'request' for TShield::Controllers::Sessions:Module (NameError)`

**To Reproduce**
1. A project with config/tshield.yml
2. When run tshield the error happens

**Traceback**
```
I, [2019-08-29T14:32:10.706933 #32583]  INFO -- : == registering /v2/keys/v1/toggles/MeuVivoEmpresas for methods get with action toggles
#<Thread:0x00007fc7e5a7b930@/Users/egarcia/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/tshield-0.11.0.0/bin/tshield:8 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        6: from /Users/egarcia/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/tshield-0.11.0.0/bin/tshield:8:in `block in <top (required)>'
        5: from /Users/egarcia/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/tshield-0.11.0.0/lib/tshield/server.rb:42:in `run!'
        4: from /Users/egarcia/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/tshield-0.11.0.0/lib/tshield/server.rb:23:in `register_resources'
        3: from /Users/egarcia/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1398:in `register'
        2: from /Users/egarcia/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1398:in `each'
        1: from /Users/egarcia/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1400:in `block in register'
/Users/egarcia/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/tshield-0.11.0.0/lib/tshield/controllers/sessions.rb:14:in `registered': undefined local variable or method `request' for TShield::Controllers::Sessions:Module (NameError)
Did you mean?  require
Traceback (most recent call last):
        6: from /Users/egarcia/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/tshield-0.11.0.0/bin/tshield:8:in `block in <top (required)>'
        5: from /Users/egarcia/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/tshield-0.11.0.0/lib/tshield/server.rb:42:in `run!'
        4: from /Users/egarcia/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/tshield-0.11.0.0/lib/tshield/server.rb:23:in `register_resources'
        3: from /Users/egarcia/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1398:in `register'
        2: from /Users/egarcia/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1398:in `each'
        1: from /Users/egarcia/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1400:in `block in register'
/Users/egarcia/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/tshield-0.11.0.0/lib/tshield/controllers/sessions.rb:14:in `registered': undefined local variable or method `request' for TShield::Controllers::Sessions:Module (NameError)
Did you mean?  require

```

**Expected behavior**
TShield should start and expose mocks :)

**Additional context**
```
$ ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin18]
```
